apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/suraj021194/argocd-example-apps
    targetRevision: HEAD
    path: argocd-helm-chart
    helm:
      values: | 
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
