{{- if .Values.job.enabled  }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "argocd-helm-chart.fullname" . }}-job
  annotations:
    "argocd.argoproj.io/hook": PreSync
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-job
          image: "{{ .Values.job.image.repository }}:{{  .Values.job.image.tag }}"
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}
          command: {{ toJson .Values.job.command }}
          args: {{ toJson .Values.job.args }}
{{- end }}
